version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: run test
          command: |
            go mod download
            go test ./... -count=1 -cover
